spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mahamdb
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


